### ISSUE TITLE
Big Data > QC Questions:

### ISSUE THREAD

**Issue by johnMedlockDev** [200413-java-spark/200413-java-spark.github.io#8]
## What (are | | is) x?

Closures:

Currying:

Recursion:

Lazy evaluations:

Spark supports two types of shared variables: 

Two ways to create RDDs:

RDDs support two types of operations:

Transformations (in relationship to RDDs):

Actions (in relationship to RDDs):

The syntax for Lambdas in Java:

A Higher-order-function:

The fastest storage level available to RDDs:

## How does x work?

All transformations in Spark are (concerning how they are evaluated):

## When would you use x?

Functional Programing:

OOP:

## Why would you use x over y?

Functional Programing  vs OOP:

Apache Spark vs Hadoop:

## How many x?

Partitions should you create for each cpu in a cluster:

## How can you x?

Speed up Spark applications:

Pass functions into driver to run on the cluster:

## List x:

Some common transformations using Spark:

Some common actions using Spark:

## Describe x:

The MapReduce Process:

How to Initializing Spark:

**Comment by GarrisonAdams** [comment]
What is an RDD?

What are the two types of operations that can be performed on RDDs? What are some examples of these two operations?

What is batch processing? What is stream processing? When would you use one other the other?

How do you persist an RDD? What methods accomplish this? What are some of the storage levels, and which is the most CPU-efficient? Why?

How do you remove an RDD?

What makes an RDD resilient?

How do you create RDDs?

How are some Apache Spark operations lazy? Which operations are lazy?

Why are accumulators necessary to count things in Spark? Why not just use a counter variable?

What Java objects do you need to create in order to initialize an Apache Spark program?

How do you implement the functions that Apache Spark uses to run a cluster?

What is a cluster? What are nodes?

What are the two types of shared variables?

What are lambda expressions? Why are they useful?

What is the MapReduce algorithm?
